name: Ruff Code Check and Format

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" 

      - name: Install Ruff
        run: |
          pip install ruff

      - name: Format Code with Ruff
        run: |
          ruff format .

      - name: Run Ruff Check
        run: |
          ruff check .
